In [5]:
### 1. imports

import torch
import random
import pandas as pd
import numpy as np 

In [7]:
## 2. Create a random tensor with shape (7, 7).

X = torch.rand(7, 7)
X, X.shape

(tensor([[0.7354, 0.9443, 0.7521, 0.4576, 0.5793, 0.3223, 0.6927],
         [0.0012, 0.1683, 0.0727, 0.8605, 0.5201, 0.8168, 0.5142],
         [0.5641, 0.8302, 0.0709, 0.1425, 0.4592, 0.0446, 0.0887],
         [0.3245, 0.9803, 0.9503, 0.6752, 0.4868, 0.3325, 0.8555],
         [0.1950, 0.5827, 0.2680, 0.4126, 0.4241, 0.9283, 0.9485],
         [0.2671, 0.4301, 0.2730, 0.9234, 0.2149, 0.2053, 0.6551],
         [0.0214, 0.7405, 0.7174, 0.5758, 0.9846, 0.3713, 0.9976]]),
 torch.Size([7, 7]))

In [14]:
## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) 
## (hint: you may have to transpose the second tensor).

Y = torch.rand(1, 7)
Y = torch.mm(X, Y.T)
Y, Y.shape

(tensor([[2.8255],
         [1.5528],
         [1.4714],
         [2.7498],
         [2.0982],
         [1.8657],
         [2.6822]]),
 torch.Size([7, 1]))

In [16]:
## 4. Set the random seed to 0 and do 2 & 3 over again.
##The output should be:

##(tensor([[1.8542],
##         [1.9611],
##         [2.2884],
##         [3.0481],
##         [1.7067],
##         [2.5290],
##         [1.7989]]), torch.Size([7, 1]))

torch.manual_seed(0)

X = torch.rand(7, 7)
Y = torch.rand(1, 7)
Y = torch.mm(X, Y.T)
Y, Y.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [19]:
## 5.   Speaking of random seeds, we saw how to set it with torch.manual_seed() 
##      but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
##      If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(1234)

In [41]:
## 6. Create two random tensors of shape (2, 3) and send them both to the GPU 
##    (you'll need access to a GPU for this). Set torch.manual_seed(1234) 
##    when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
##    Device: cuda
##    (tensor([[0.0290, 0.4019, 0.2598],
##           [0.3666, 0.0583, 0.7006]], device='cuda:0'),
##     tensor([[0.0518, 0.4681, 0.6738],
##           [0.3315, 0.7837, 0.5631]], device='cuda:0'))


# Set random seed
torch.cuda.manual_seed(1234)
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
X = torch.rand(2,3).to(device)
Y = torch.rand(2,3).to(device)
X, Y

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [42]:
## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
##     The output should look like:
##    (tensor([[0.3647, 0.4709],
##           [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

Z = torch.mm(X, Y.T)
Z, Z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [45]:
## 8. Find the maximum and minimum values of the output of 7.

Zmax = Z.max()
Zmin = Z.min()
print("Max val: ", Zmax)
print("Min val: ", Zmin)

Max val:  tensor(0.5617, device='cuda:0')
Min val:  tensor(0.3647, device='cuda:0')


In [46]:
## 9. Find the maximum and minimum index values of the output of 7.

Zargmax = Z.argmax()
Zargmin = Z.argmin()
print("Max pos: ", Zargmax)
print("Min pos: ", Zargmin)

Max pos:  tensor(3, device='cuda:0')
Min pos:  tensor(0, device='cuda:0')


In [49]:
##  10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor 
##      with all the 1 dimensions removed to be left with a tensor of shape (10). 
##      Set the seed to 7 when you create it and print out the first tensor 
##      and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)

X = torch.rand(1, 1, 1, 10)
Y = X.squeeze()

print(X, X.shape)
print(Y, Y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
