In [1]:
## 00. PyTorch Fundamentals
## Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [97]:
import  torch
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
print("gpu:", torch.cuda.get_device_name(0))

torch: 2.11.0+cu126
cuda available: True
gpu: NVIDIA GeForce RTX 4080 SUPER


In [98]:
x = torch.randn(3000, 3000).cuda()
y = torch.randn(3000, 3000).cuda()

z = x @ y

print(z.device)


cuda:0


In [99]:
# Introduction to Tensors
# Creating Tensors

## Tensors torch.tensor(): https://docs.pytorch.org/docs/2.11/tensors.html

In [100]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [101]:
scalar.ndim

0

In [102]:
#Get trnsor back as Python int
scalar.item()

7

In [103]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [104]:
vector.ndim

1

In [105]:
vector.shape

torch.Size([2])

In [106]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [107]:
MATRIX.ndim

2

In [108]:
MATRIX[0]

tensor([7, 8])

In [109]:
MATRIX.shape

torch.Size([2, 2])

In [110]:
# TENSOR = torch.tensor([[[1,2,3],
TENSOR = torch.tensor([[[1,2,3],
                        [4, 5, 6],
                        [7, 8, 9]],
                      [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]])
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])

In [111]:
TENSOR.ndim

3

In [112]:
TENSOR.shape


torch.Size([2, 3, 3])

In [113]:
### RANDOM TENSORS

random_tensor = torch.rand(size=(2, 3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.8970, 0.3815, 0.3248, 0.7574],
          [0.0609, 0.0885, 0.7014, 0.1136],
          [0.6372, 0.2943, 0.2820, 0.7002]],
 
         [[0.8386, 0.6167, 0.2933, 0.9467],
          [0.0876, 0.6222, 0.4993, 0.6871],
          [0.5043, 0.1229, 0.8071, 0.6142]]]),
 torch.float32)

In [114]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [115]:
## Tensor with zeros

zeros = torch.zeros(size=(2, 2, 2))
zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [116]:
## Tensor with ones

ones = torch.ones(size=(2, 2, 2))
ones

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [117]:
## Creating ranged tensor

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [119]:
## create tensor with specific data type

float_32_tensor = torch.tensor([3, 6, 9],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [120]:
float_16_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [121]:
# Getting information from tensors

some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape: {some_tensor.shape}")
print(f"Datatype: {some_tensor.dtype}")
print(f"Device:  {some_tensor.device}")

tensor([[0.1468, 0.5985, 0.3568, 0.1247],
        [0.8634, 0.0937, 0.6186, 0.2057],
        [0.3090, 0.6452, 0.9263, 0.1199]])
Shape: torch.Size([3, 4])
Datatype: torch.float32
Device:  cpu


In [122]:
## add, minus, multiply
tensor = torch.tensor([2,5,6])
tensor_add = tensor + 5
tensor_minus = tensor - 5
tensor_mult = tensor * 5
tensor_div = tensor / 5
tensor_addf = torch.add(tensor, 5)
tensor_multf = torch.multiply(tensor, 5)
tensor_add, tensor_minus, tensor_mult, tensor_div, tensor_addf, tensor_multf

(tensor([ 7, 10, 11]),
 tensor([-3,  0,  1]),
 tensor([10, 25, 30]),
 tensor([0.4000, 1.0000, 1.2000]),
 tensor([ 7, 10, 11]),
 tensor([10, 25, 30]))

In [123]:
## Matrix multiplication, most common operation
## torch.matmul()
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [124]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [125]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [126]:

### MAKE SURE SHAPES IS CORRECT

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [127]:

### ONE OF THE WAYS TO FIX IT IS TO TRANSPOSE ONE OF MATRICES, USING .T

tensor_A.shape, tensor_B.shape, tensor_B.T.shape

##after this operation we can do @ operaton

(torch.Size([3, 2]), torch.Size([3, 2]), torch.Size([2, 3]))

In [128]:
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [129]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [130]:
tensor23 = torch.tensor([[1,2,3],
                        [4,5,6]])
tensor33 = torch.tensor([[3,6,9],
                        [1,4,7],
                        [2,5,8]])
torch.mm(tensor23, tensor33)

tensor([[ 11,  29,  47],
        [ 29,  74, 119]])

In [131]:

### Finding the min, max, mean, sum, etc (aggregation)



In [132]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [133]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [134]:
tensor = torch.arange(0,100,5)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])
Index where max value occurs: 19
Index where min value occurs: 0


In [135]:

## Change tensor datatype if tensors in different datatypes.

# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype


torch.float32

In [136]:
tensor_16 = tensor.type(torch.float16)
tensor_16


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [137]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [138]:


### Reshaping, stacking, squeezing and unsqueezing



In [139]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [140]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [141]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape, x

(tensor([[1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [142]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [143]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [144]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [145]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [146]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [147]:



### Indexing (selecting data from tensors)




In [148]:
#Create tensor

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [149]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][2][2]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 9


In [150]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [151]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [152]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [153]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [154]:



### PyTorch tensors & NumPy




In [155]:
#NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [156]:
## By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
## However, many PyTorch calculations default to using float32.
## tensor = torch.from_numpy(array).type(torch.float32)


In [157]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [158]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [159]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [160]:



### Reproducibility (trying to take the random out of random)




In [161]:
# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")

random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7230, 0.7337, 0.0810, 0.0779],
        [0.6607, 0.9344, 0.8462, 0.3297],
        [0.6695, 0.9651, 0.7375, 0.6688]])

Tensor B:
tensor([[0.3191, 0.2721, 0.5318, 0.3290],
        [0.5845, 0.4038, 0.8158, 0.2688],
        [0.1451, 0.6537, 0.8695, 0.8982]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [163]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [165]:


###  Running tensors on GPUs (and making faster computations)



!nvidia-smi

Thu May  7 14:55:01 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.86                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   28C    P8              5W /  320W |    1458MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [166]:
torch.cuda.is_available()

True

In [167]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [168]:
# Count number of devices
torch.cuda.device_count()

1

In [169]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [170]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [171]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

In [172]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')