In [13]:
## 00. PyTorch Fundamentals
## Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [14]:
import  torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
print("gpu:", torch.cuda.get_device_name(0))

torch: 2.11.0+cu126
cuda available: True
gpu: NVIDIA GeForce RTX 4080 SUPER


In [15]:
x = torch.randn(3000, 3000).cuda()
y = torch.randn(3000, 3000).cuda()

z = x @ y

print(z.device)


cuda:0


In [16]:
# Introduction to Tensors
# Creating Tensors

## Tensors torch.tensor(): https://docs.pytorch.org/docs/2.11/tensors.html

In [17]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [18]:
scalar.ndim

0

In [19]:
#Get trnsor back as Python int
scalar.item()

7

In [20]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [25]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [27]:
MATRIX[0]

tensor([7, 8])

In [29]:
MATRIX.shape

torch.Size([2, 2])

In [37]:
# TENSOR = torch.tensor([[[1,2,3],
TENSOR = torch.tensor([[[1,2,3],
                        [4, 5, 6],
                        [7, 8, 9]],
                      [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]])
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])

In [38]:
TENSOR.ndim

3

In [39]:
TENSOR.shape


torch.Size([2, 3, 3])

In [41]:
### RANDOM TENSORS

random_tensor = torch.rand(size=(2, 3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.3726, 0.6445, 0.9205, 0.4190],
          [0.9228, 0.1554, 0.3317, 0.1846],
          [0.1738, 0.5729, 0.5012, 0.7494]],
 
         [[0.2352, 0.7339, 0.4088, 0.6225],
          [0.2684, 0.6479, 0.5007, 0.5182],
          [0.5897, 0.2796, 0.3806, 0.4774]]]),
 torch.float32)

In [42]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [45]:
## Tensor with zeros

zeros = torch.zeros(size=(2, 2, 2))
zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [46]:
## Tensor with ones

ones = torch.ones(size=(2, 2, 2))
ones

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [47]:
## Creating ranged tensor

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
## create tensor with specific data type

float_32_tensor = torch.tensor([3, 6, 9],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [50]:
float_16_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [51]:
# Getting information from tensors

some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape: {some_tensor.shape}")
print(f"Datatype: {some_tensor.dtype}")
print(f"Device:  {some_tensor.device}")

tensor([[0.2771, 0.4907, 0.1656, 0.2828],
        [0.4100, 0.7634, 0.8801, 0.0152],
        [0.4727, 0.2137, 0.1230, 0.8807]])
Shape: torch.Size([3, 4])
Datatype: torch.float32
Device:  cpu


In [53]:
## add, minus, multiply
tensor = torch.tensor([2,5,6])
tensor_add = tensor + 5
tensor_minus = tensor - 5
tensor_mult = tensor * 5
tensor_div = tensor / 5
tensor_addf = torch.add(tensor, 5)
tensor_multf = torch.multiply(tensor, 5)
tensor_add, tensor_minus, tensor_mult, tensor_div, tensor_addf, tensor_multf

(tensor([ 7, 10, 11]),
 tensor([-3,  0,  1]),
 tensor([10, 25, 30]),
 tensor([0.4000, 1.0000, 1.2000]),
 tensor([ 7, 10, 11]),
 tensor([10, 25, 30]))

In [54]:
## Matrix multiplication, most common operation
## torch.matmul()
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [55]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [56]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [57]:

### MAKE SURE SHAPES IS CORRECT

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [63]:

### ONE OF THE WAYS TO FIX IT IS TO TRANSPOSE ONE OF MATRICES, USING .T

tensor_A.shape, tensor_B.shape, tensor_B.T.shape

##after this operation we can do @ operaton

(torch.Size([3, 2]), torch.Size([3, 2]), torch.Size([2, 3]))

In [64]:
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [65]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [70]:
tensor23 = torch.tensor([[1,2,3],
                        [4,5,6]])
tensor33 = torch.tensor([[3,6,9],
                        [1,4,7],
                        [2,5,8]])
torch.mm(tensor23, tensor33)

tensor([[ 11,  29,  47],
        [ 29,  74, 119]])

In [71]:

### Finding the min, max, mean, sum, etc (aggregation)



In [72]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [75]:
tensor = torch.arange(0,100,5)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])
Index where max value occurs: 19
Index where min value occurs: 0


In [76]:

## Change tensor datatype if tensors in different datatypes.

# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype


torch.float32

In [77]:
tensor_16 = tensor.type(torch.float16)
tensor_16


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [78]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)